[package]
name = "problems_99"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
factorial = "0"
itertools = "0"
num = "0"
num-integer = "0"
rand = "0"

[dev-dependencies]
proptest = "1"